name: Release (by Tag Push)

'on':
  push:
    tags:
      - '*'

jobs:

  deploy:
    name: Deploy
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache .cache/pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: pip_cache_py_${{ matrix.python-version }}
    - uses: casperdcl/deploy-pypi@v2
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        build: --sdist --wheel --outdir dist .
